# SPDX-FileCopyrightText: 2026 Copyright (c) Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
name: 'Format and Clippy'
description: 'Run rustfmt check and clippy'
inputs:
  toolchain:
    description: >-
      Rust toolchain to use for rustfmt and clippy (e.g. "stable", "nightly", or "nightly-2025-07-14"). Defaults to "stable".
    required: false
    default: 'stable'
  extra-args:
    description: 'Additional arguments passed to cargo clippy (e.g. "--all-features" or "--all-features --all-targets")'
    required: false
    default: '--all-features --all-targets --locked -- --deny=warnings'

runs:
  using: 'composite'
  steps:
    - name: Install Rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: ${{ inputs.toolchain }}
        components: clippy, rustfmt
        cache-shared-key: ${{ inputs.toolchain }}
        rustflags: ""

    - name: Format check (rustfmt)
      id: fmt
      # Set to 'true' to present all errors to user at once, 'false' fails immediately.
      continue-on-error: true
      shell: bash
      run: cargo +${{ inputs.toolchain }} fmt --check

    - name: Clippy
      id: clippy
      # Set to 'true' to present all errors to user at once, 'false' fails immediately.
      continue-on-error: true

      shell: bash
      run: cargo +${{ inputs.toolchain }} clippy --locked ${{ inputs.extra-args }}

    - name: Fail if format check failed
      if: ${{ steps.fmt.outcome == 'failure' }}
      shell: bash
      run: |
        echo "::error::Format check failed. Run 'cargo +${{ inputs.toolchain }} fmt' to fix formatting issues."
        exit 1

    - name: Fail if clippy found warnings
      if: ${{ steps.clippy.outcome == 'failure' }}
      shell: bash
      run: exit 1
