name: CI Checks

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  pre-commit-job:
    runs-on: ubuntu-latest
    steps:
      - name: Run shared pre-commit checks
        uses: alexmohr/cicd-workflows/pre-commit-action@init 
  
  check-headers:
    runs-on: ubuntu-latest
    steps:
      - name: Run shared license header check
        uses: alexmohr/cicd-workflows/license-header-check-action@init